### ISSUE TITLE
QUESTION: how to get the string from the encode function

### ISSUE THREAD

**Issue by woss** [multiformats/js-multibase#67]
in version `1.0.0` we could use `encode(buff).toString()` and then we would get something similar to this `bfuws2ljnijcuoskoebieoubakbkuetcjimqewrkzebbeyt2djmws2ljnfugquvtfojzws33ohiqe64dfnzieoubonjzsa5rufyytalrybufeg33nnvsw45b2ebuhi5dqom5c6l3pobsw44dhobvhgltpojtq2csdn5ww2zlooq5cavdinfzsa2ltebqsa4tfozxwgylunfxw4iddmvzhi2lgnfrwc5dfbufa2ctxnztukskclf.....`

how to get the same thing in current version?
Thanks

**Comment by rvagg** [comment]
I think you're running into the problem of not having a `'hex'` serializer for `Uint8Arrays` - in the previous version we exported `Buffer` objects which can do a native `toString('hex')`, now we export a `Uint8Array` which has a subset of the `Buffer` functionality (which is just a wrapper around `Uint8Array). This is all done because it means browser users don't need to pull in the entire `Buffer` polyfill if they don't want - at least this library won't for you to do that.

What you can do, if you're on Node or want to pull in that polyfill is pass it through `Buffer`: `Buffer.from(buf).toString('hex')` and you'll get the polyfill. Or you could pull in a light polyfill for this purpose, such as `uint8arrays` which has a `toString()` method that will do most of the things `Buffer#toString()` will do: https://github.com/achingbrain/uint8arrays#tostringarray-encoding--utf8:

```
const toString = require('uint8arrays/from-string')
toString(buf, 'base16')
```

Or roll your own if perf isn't a high priority, such as this one-liner: https://github.com/multiformats/js-multiformats/blob/b0eca3c1384abd22afa2cdf7e37c63468c535001/src/bytes.js#L1

**Comment by woss** [comment]
gotcha! 

so you took away the functionality from the multibase and offloaded this to the users of the lib.

not sure do i agree with that though I would if that would bring the package smaller size and speed but based on this it doesn't.
<img width="1073" alt="Annotation 2020-09-09 121245" src="https://user-images.githubusercontent.com/80440/92585996-f6a0be80-f295-11ea-9680-8ada8e96fd79.png">

I use CID extensively and build on top of it and `multi*` and now i have 2 diff versions of multibase, 3 that comes with new CID and 1 that i use independently.  you can totally say why am i complaining since it is a major version change, i wouldn't if you were so kind to make migration doc ( maybe you have it, in that case put it in obvious place , top of readme file )  and add more example, not EVERYONE will multibase the text.

**Comment by vmx** [comment]
> not sure do i agree with that though I would if that would bring the package smaller size and speed but based on this it doesn't.

The breaking change was a step towards a smaller bundle size. Next step (a non-breaking change) is getting also the `Buffer` dependency removed from other dependencies. This work happens at https://github.com/multiformats/js-multibase/pull/64. Once that is merged, the bundle size will be smaller.

**Comment by woss** [comment]
thanks for clearing that out. but why did you ditch the functionality `toString()` just because of the size?

**Comment by vmx** [comment]
>  but why did you ditch the functionality `toString()` just because of the size?

The reason wasn't size. The reason is that we want the JS libraries to be Browser first libraries that don't use Node.js APIs that need to be polyfilled. Removing the dependency on `Buffer` is a step into that direction.

`toString()` wasn't really multibase functionality, but one of [Node.js Buffer](https://nodejs.org/docs/latest-v14.x/api/buffer.html#buffer_buf_tostring_encoding_start_end).

**Comment by woss** [comment]
yes that's true, now it makes sense for the browsers, but this breaks the nodejs. here is the [runkit](https://runkit.com/woss/5f53b86fea3c56001aa6cb26) where i made 2 examples, browser and node, based on the readme and what was written in the comments. 

i know people are compiling the packages for bot the node and browser, couldn't you guys do the same?

**Comment by vmx** [comment]
> yes that's true, now it makes sense for the browsers, but this breaks the nodejs

How does it break in Node.js? I know in Node.js it's common to use `Buffer`, but even there you could just use `Uint8Array` directly.

From your example it has the exact same behaviour in the Browser and on Node.js. And if you want to have the `toString('hex')` functionality, you can wrap it in `Buffer.from()`, just as you did.

If you do a Browser based application, you could also load the `Buffer` polyfill yourself to get that functionality.


> i know people are compiling the packages for bot the node and browser, couldn't you guys do the same?

We do compile for the Browser, but we don't want to have a large Polyfills in there for stuff that can be done without.

**Comment by woss** [comment]
Thanks @vmx for patient explanation. i need to familiar myself more on this topic `Uint8Array` `Buffers` and differences in the Browser and Node approach. I still don't understand FULLY but i will check the code when i have time, maybe then i can get the proper grasp of the problem. 

Also if you don't mind checking that example i sent earlier and see what am i doing wrong when changing the base.

**Comment by vmx** [comment]
Do you mean the [runkit](https://runkit.com/woss/5f53b86fea3c56001aa6cb26) example? I don't understand what you mean with "changing the base".

**Comment by woss** [comment]
yes, there is a comment on the line where the 

```js
const baseEnc = 'base32' // how come base58btc shows correct decoded bytes? try to change the baseEnc
``` 
is defined

When i have the  `const baseEnc = 'base32'` the decode function returns the bytearray string, and when i have `const baseEnc = 'base58btc '` it returns the string that was passed in the TextEncoder.

**Comment by vmx** [comment]
That's due to https://github.com/multiformats/js-multibase/pull/64. Once fixed, it will always return a `Uint8Array` instead of a Node.js `Buffer`.

**Comment by woss** [comment]
aha, many thanks!
